#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#index:
#    path: /
#    controller: App\Controller\GestionEtudiantController::index

api_login_check:
  path: /api/login
  methods: ["POST"]
